name: Testes com Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Detectar e baixar EdgeDriver compatível
        shell: pwsh
        run: |
          $edgePath = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
          $edgeVersion = (Get-Item $edgePath).VersionInfo.FileVersion
          Write-Host "Versão do Edge: $edgeVersion"

          $major = $edgeVersion.Split('.')[0]
          Write-Host "Versão major: $major"

          # Obter a versão do EdgeDriver com codificação correta
          $response = Invoke-WebRequest -Uri "https://msedgedriver.azureedge.net/LATEST_RELEASE_$major"
          $driverVersion = $response.Content.Trim()
          Write-Host "Versão do EdgeDriver: $driverVersion"

          $driverUrl = "https://msedgedriver.azureedge.net/$driverVersion/edgedriver_win64.zip"
          Write-Host "Baixando EdgeDriver de: $driverUrl"

          Invoke-WebRequest -Uri $driverUrl -OutFile "edgedriver.zip"

          Expand-Archive -Path "edgedriver.zip" -DestinationPath "edgedriver" -Force

          $edgedriverPath = Resolve-Path ".\edgedriver"
          echo "$edgedriverPath" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Executar testes
        run: dotnet test
