name: Executar Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Instalar Microsoft Edge
      run: choco install microsoft-edge -y

    - name: Baixar e configurar EdgeDriver compatível
      shell: bash
      run: |
        # Detectar versão do Microsoft Edge
        EDGE_VERSION=$(powershell "[System.Diagnostics.FileVersionInfo]::GetVersionInfo('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe').FileVersion")
        echo "Detectada versão do Edge: $EDGE_VERSION"

        # Extrair major version (ex: 136)
        EDGE_MAJOR_VERSION=$(echo $EDGE_VERSION | cut -d'.' -f1)
        echo "Versão major do Edge: $EDGE_MAJOR_VERSION"

        # Buscar última versão do EdgeDriver compatível
        EDGE_DRIVER_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_RELEASE_$EDGE_MAJOR_VERSION)
        echo "Versão do EdgeDriver: $EDGE_DRIVER_VERSION"

        # Baixar e extrair o driver
        DRIVER_URL="https://msedgedriver.azureedge.net/${EDGE_DRIVER_VERSION}/edgedriver_win64.zip"
        echo "Baixando EdgeDriver de: $DRIVER_URL"

        curl -L -o edgedriver.zip "$DRIVER_URL"

        # Validar e extrair ZIP
        if ! unzip -t edgedriver.zip; then
          echo "Falha ao baixar ou validar o EdgeDriver."
          exit 1
        fi

        unzip edgedriver.zip -d edgedriver
        echo "$(pwd)/edgedriver" >> $GITHUB_PATH

    - name: Executar testes
      run: dotnet test --no-build --verbosity normal
