name: Executar Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Instalar Microsoft Edge (se necessário)
      run: choco install microsoft-edge -y

    - name: Baixar e configurar EdgeDriver manualmente
      shell: bash
      run: |
        EDGE_VERSION=$(powershell "(Get-AppxPackage -Name Microsoft.MicrosoftEdge.Stable).Version")
        EDGE_MAJOR_VERSION=$(echo $EDGE_VERSION | cut -d'.' -f1)
        echo "Detectada versão do Edge: $EDGE_VERSION (maior: $EDGE_MAJOR_VERSION)"

        curl -L -o edgedriver.zip https://msedgedriver.azureedge.net/${EDGE_MAJOR_VERSION}.0.0.0/edgedriver_win64.zip
        unzip edgedriver.zip -d edgedriver
        echo "$(pwd)/edgedriver" >> $GITHUB_PATH

    - name: Executar testes
      run: dotnet test --no-build --verbosity normal
