name: Rodar Todos os Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Obter versão do Edge e baixar EdgeDriver
        shell: pwsh
        run: |
          $edgePaths = @(
            "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
            "C:\Program Files\Microsoft\Edge\Application\msedge.exe"
          )

          $edgePath = $edgePaths | Where-Object { Test-Path $_ } | Select-Object -First 1

          if (-not $edgePath) {
            Write-Error "Microsoft Edge não encontrado."
            exit 1
          }

          Write-Host "Edge encontrado em: $edgePath"

          # Obter versão do executável
          $fileVersionInfo = (Get-Item $edgePath).VersionInfo
          $edgeVersion = $fileVersionInfo.FileVersion
          $majorVersion = $edgeVersion.Split('.')[0]

          Write-Host "Versão do Edge: $edgeVersion"
          Write-Host "Versão major: $majorVersion"

          $driverUrl = "https://msedgedriver.azureedge.net/$edgeVersion/edgedriver_win64.zip"
          Write-Host "Baixando EdgeDriver de: $driverUrl"

          Invoke-WebRequest -Uri $driverUrl -OutFile "edgedriver.zip"
          Expand-Archive -Path "edgedriver.zip" -DestinationPath "C:\edgedriver"
          echo "C:\edgedriver" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Instalar dependências
        run: dotnet restore

      - name: Rodar todos os testes (incluindo Selenium)
        run: dotnet test --configuration Release --verbosity normal
        timeout-minutes: 5